apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: agent
    port: 50000
    targetPort: 50000
    nodePort: 30050
# 외부 브라우저에서 30080 포트로 들어오고 service 규칙에 클러스터의 8080으로 들어온 트래픽은 젠킨스 파드의 8080으로 보내라
# selector의 jenkins로 젠킨스 파드임을 알 수 있음, jenkins deployment에도 template: metadata: labels: app: jenkins 로 jenkins임을 명시하고 있음
