# 젠킨스 데이터 저장용 볼륨, k3s는 설치할 때 pv 자동 생성됨
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
