server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;

        location ~* \.js\.gz$ {
            add_header Content-Encoding gzip;
            add_header Content-Type application/javascript;
        }

        location ~* \.wasm\.gz$ {
            add_header Content-Encoding gzip;
            add_header Content-Type application/wasm;
        }

        location ~* \.data\.gz$ {
            add_header Content-Encoding gzip;
            add_header Content-Type application/octet-stream;
        }

        location ~* \.symbols\.json\.gz$ {
            add_header Content-Encoding gzip;
            add_header Content-Type application/json;
        }
    }
}
