name: Unity WebGL Build & Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 디스크 공간 확보
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune -af
          df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
        # uses는 미리 만들어진 액션을 가져다 쓴다는 뜻이에요. 
        # actions/checkout@v4는 GitHub 공식 액션이에요. 
        # lfs: true는 Git LFS로 관리되는 대용량 파일(유니티 에셋 등)도 같이 받아오는 옵션
      
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildName: webgl-build

      # build Job이 끝나면 서버가 사라지기 때문에 
      # deploy Job으로 파일을 넘기려면 여기에 저장해둬야 해요
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webgl-build
          path: build/WebGL

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webgl-build
          path: build/WebGL

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 & 푸시
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t makbeom/webgl-app:${{ github.sha }} \
            --push .

      - name: 라즈베리파이 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PI_IP }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT }}
          script: |
            kubectl set image deployment/webgl-app \
              webgl-app=makbeom/webgl-app:${{ github.sha }}
